version: "3.3"
  
services:  
  gamifydb:
    container_name: gamifydb
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/gamifydb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_DATABASE=gamifydb

  wavesdb:
    container_name: wavesdb
    image: mariadb
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./db/wavesdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_DATABASE=wavesdb

  redis:
    container_name: cache_messagebroker
    image: redis
    expose:
      - 6379

  gamify-backend:
    image: waves-backend
    container_name: gamify-backend
    restart: always
    build:
      context: ./gamify-backend
      dockerfile: Dockerfile
    volumes:
        - ./gamify-backend:/usr/src/app
        - /usr/src/app/node_modules 
    depends_on:
      - gamifydb
      - redis
    ports:
      - "5000:5000"
    environment: 
      - NODE_ENV=production

      - OAUTH_BASE_URI=https://stage.vivaconagua.org
      
      - CLIENT_ID=wavesvtwo
      - CLIENT_SECRET=clientwavesvtwo
      - REDIRECT_URI=http://localhost:9000/backend/waves/api/v1/oauth
      
      - REDIRECT_URI_PRODUCTION=https://stage.vivaconagua.org/backend/waves/api/v1/oauth
      - CLIENT_ID_PRODUCTION=wavesvtwo
      - CLIENT_SECRET_PRODUCTION=clientwavesvtwo

      - PORT=5000
      - HOST=localhost
      - USER_NAME=root
      - PASSWORD=password
      - DATABASE=gamifydb

      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
      
  waves-backend:
    image: waves-backend
    container_name: waves-backend
    restart: always
    build:
      context: ./waves-backend
      dockerfile: Dockerfile
    volumes:
        - ./waves-backend:/usr/src/app
        - /usr/src/app/node_modules 
    depends_on:
      - gamifydb
      - redis
    ports:
      - "4000:4000" 
    environment: 
      - NODE_ENV=dev

      - OAUTH_BASE_URI=https://stage.vivaconagua.org

      - CLIENT_ID=wavesvtwo
      - CLIENT_SECRET=clientwavesvtwo
      - REDIRECT_URI=http://localhost:9000/backend/waves/api/v1/oauth
      
      - REDIRECT_URI_PRODUCTION=https://stage.vivaconagua.org/backend/waves/api/v1/oauth
      - CLIENT_ID_PRODUCTION=wavesvtwo
      - CLIENT_SECRET_PRODUCTION=clientwavesvtwo

      - PORT=5000
      - HOST=localhost
      - USER_NAME=root
      - PASSWORD=password
      - DATABASE=wavesdb

      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379

  nginx: 
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  waves-frontend:
    image: waves-frontend
    container_name: waves-frontend
    build:
      context: ./waves-frontend
    ports:
      - '8080:8080'
    volumes:
      - './waves-frontend:/app'
    command: "/bin/sh -c "serve -p 8080 -s dist"
        