version: "3"
  
services:  
  gamifydb:
    container_name: gamifydb
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/gamifydb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_DATABASE=gamifydb

  wavesdb:
    container_name: wavesdb
    image: mariadb
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./db/wavesdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_DATABASE=wavesdb

  redis:
    container_name: cache_messagebroker
    image: redis
    expose:
      - 6379

  gamify-backend:
    container_name: gamify-backend
    restart: always
    build:
      context: ./gamify-backend
      dockerfile: Dockerfile.dev
    volumes:
        - ./gamify-backend:/usr/src/app
        - /usr/src/app/node_modules 
    depends_on:
      - gamifydb
      - redis
    ports:
      - "5000:5000"  
  waves-backend:
    container_name: waves-backend
    restart: always
    build:
      context: ./waves-backend
      dockerfile: Dockerfile.dev
    volumes:
        - ./waves-backend:/usr/src/app
        - /usr/src/app/node_modules 
    depends_on:
      - gamifydb
      - redis
    ports:
      - "4000:4000" 
    environment: 
      - OAUTH_BASE_URI=https://stage.vivaconagua.org
      - REDIRECT_URI=http://localhost/backend/waves/api/v1/oauth
      - CLIENT_ID=waves
      - CLIENT_SECRET=977bde90-6707-11ea-bc55-0242ac130003
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
        