version: '3'

services:
  gamifydb:
    container_name: gamifydb
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/gamifydb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_DATABASE=gamifydb

  wavesdb:
    container_name: wavesdb
    image: mariadb
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./db/wavesdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_DATABASE=wavesdb

  redis:
    container_name: cache_messagebroker
    image: redis
    expose:
      - 6379

  gamify-backend:
    image: waves-backend
    container_name: gamify-backend
    restart: always
    build:
      context: ./gamify-backend
      dockerfile: Dockerfile
    volumes:
        - ./gamify-backend:/usr/src/app
        - /usr/src/app/node_modules 
    depends_on:
      - gamifydb
      - redis
    ports:
      - "5000:5000"
    environment: 
      - NODE_ENV=production

      - OAUTH_BASE_URI=https://stage.vivaconagua.org
      
      - CLIENT_ID=wavesvtwo
      - CLIENT_SECRET=clientwavesvtwo
      - REDIRECT_URI=http://localhost:9000/backend/waves/api/v1/oauth
      
      - REDIRECT_URI_PRODUCTION=https://stage.vivaconagua.org/backend/waves/api/v1/oauth
      - CLIENT_ID_PRODUCTION=wavesvtwo
      - CLIENT_SECRET_PRODUCTION=clientwavesvtwo

      - PORT=5000
      - HOST=localhost
      - USER_NAME=root
      - PASSWORD=password
      - DATABASE=gamifydb

      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
      
  waves-backend:
    image: waves-backend
    container_name: waves-backend
    restart: always
    build:
      context: ./waves-backend
      dockerfile: Dockerfile
    volumes:
        - ./waves-backend:/usr/src/app
        - /usr/src/app/node_modules 
    depends_on:
      - gamifydb
      - redis
    ports:
      - "4000:4000" 
    environment: 
      - NODE_ENV=dev

      - OAUTH_BASE_URI=https://stage.vivaconagua.org

      - CLIENT_ID=waveseval
      - CLIENT_SECRET=waveseval
      - REDIRECT_URI=http://164.90.191.26/backend/waves/api/v1/oauth
      
      - REDIRECT_URI_PRODUCTION=http://164.90.191.26/backend/waves/api/v1/oauth
      - CLIENT_ID_PRODUCTION=waveseval
      - CLIENT_SECRET_PRODUCTION=waveseval

      - PORT=5000
      - HOST=localhost
      - USER_NAME=root
      - PASSWORD=password
      - DATABASE=wavesdb

      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on:
        - waves-frontend
        - waves-backend
        - gamify-backend
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

      # Generates a precipitation estimate
  waves-frontend:
    image: waves-frontend
    container_name: waves-frontend
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192
    build:
      context: ./waves-frontend
    ports:
      - 5002:5002
    restart: on-failure
    